package com.shen.testeverything.model;

public class Classes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column classes.classes
     *
     * @mbggenerated
     */
    private Integer classes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.id
     *
     * @return the value of classes.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.id
     *
     * @param id the value for classes.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column classes.classes
     *
     * @return the value of classes.classes
     *
     * @mbggenerated
     */
    public Integer getClasses() {
        return classes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column classes.classes
     *
     * @param classes the value for classes.classes
     *
     * @mbggenerated
     */
    public void setClasses(Integer classes) {
        this.classes = classes;
    }
}