package com.shen.testeverything.model;

public class Source {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source.source
     *
     * @mbggenerated
     */
    private Integer source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source.kecheng
     *
     * @mbggenerated
     */
    private String kecheng;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source.id
     *
     * @return the value of source.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source.id
     *
     * @param id the value for source.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source.source
     *
     * @return the value of source.source
     *
     * @mbggenerated
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source.source
     *
     * @param source the value for source.source
     *
     * @mbggenerated
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source.kecheng
     *
     * @return the value of source.kecheng
     *
     * @mbggenerated
     */
    public String getKecheng() {
        return kecheng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source.kecheng
     *
     * @param kecheng the value for source.kecheng
     *
     * @mbggenerated
     */
    public void setKecheng(String kecheng) {
        this.kecheng = kecheng;
    }
}