package com.shen.testeverything.mapper;

import com.shen.testeverything.model.Source;

public interface SourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated
     */
    int insert(Source record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated
     */
    int insertSelective(Source record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated
     */
    Source selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Source record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Source record);
}